# code: language=ansible
---
- name: Install, configure and setup podman and compose
  block:
    - name: Update apt packages
      ansible.builtin.import_role:
        name: update-packages

    - name: Install podman
      ansible.builtin.apt:
        name: podman
        state: present
      notify:
        - Configure podman
        - Set minimum unprivileged port

    - name: Download docker compose standalone
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: a+x
      notify:
        - Enable and configure podman socket
  become: true
