# code: language=ansible
---
- name: Install and setup ufw
  block:
    - name: Update and upgrade apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes

    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present
      notify:
        - "Configure ufw"
  become: true