# code: language=ansible
---
- name: Install and setup ufw
  block:
    - ansible.builtin.import_role:
        name: update-packages

    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present
      notify:
        - "Configure ufw"
  become: true
